version: '3.4'

services:
  db:
    restart: unless-stopped
    container_name: psql-11-dvs
    image: mdillon/postgis:11-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
