# Generated by Django 2.0.4 on 2019-08-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sector_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subsector',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sector', to='core.Sector'),
        ),
    ]
