# Generated by Django 2.0.4 on 2019-08-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_program_sub_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marker_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkerValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marekr_values', models.CharField(blank=True, max_length=100, null=True)),
                ('marker_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarkerCategory', to='core.MarkerCategory')),
            ],
        ),
    ]
