# Generated by Django 2.0.4 on 2019-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_markercategory_markervalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='marker',
        ),
        migrations.AddField(
            model_name='program',
            name='marker',
            field=models.ManyToManyField(blank=True, null=True, related_name='MarkerValues', to='core.MarkerValues'),
        ),
    ]
