# Generated by Django 2.0.4 on 2019-08-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190812_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markercategory',
            old_name='Marker_category',
            new_name='marker_category',
        ),
        migrations.RenameField(
            model_name='markervalues',
            old_name='marekr_values',
            new_name='marker_values',
        ),
    ]
