# Generated by Django 2.0.4 on 2019-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190813_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='marker',
            field=models.ManyToManyField(blank=True, related_name='MarkerValues', to='core.MarkerValues'),
        ),
    ]
