# Generated by Django 2.0.4 on 2019-08-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('core', '0008_auto_20190813_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Partner',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='organization_address',
            new_name='partner_address',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='organization_description',
            new_name='partner_description',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='organization_name',
            new_name='partner_name',
        ),
    ]
