# Generated by Django 2.0.4 on 2019-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190819_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
