# Generated by Django 2.0.4 on 2019-08-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fivew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FProvince', to='core.Province'),
        ),
    ]
