# Generated by Django 2.0.4 on 2019-08-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190820_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDistrict', to='core.District'),
        ),
        migrations.AlterField(
            model_name='fivew',
            name='gapa_napa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GapaNapa', to='core.GapaNapa'),
        ),
    ]
