# Generated by Django 2.0.4 on 2019-08-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190820_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='implenting_partner_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FPartner', to='core.Partner'),
        ),
    ]
