# Generated by Django 2.0.4 on 2019-08-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fivew_implenting_partner_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='implenting_partner_fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FOPartner', to='core.Partner'),
        ),
        migrations.AddField(
            model_name='fivew',
            name='implenting_partner_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SPartner', to='core.Partner'),
        ),
        migrations.AddField(
            model_name='fivew',
            name='implenting_partner_third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TPartner', to='core.Partner'),
        ),
    ]
