# Generated by Django 2.0.4 on 2019-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190822_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='rp_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='rp_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='rp_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
