# Generated by Django 2.0.4 on 2019-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190823_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, max_length=100, null=True)),
                ('full_title', models.CharField(blank=True, max_length=100, null=True)),
                ('federal_level', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
