# Generated by Django 2.0.4 on 2019-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190903_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='abstract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
