# Generated by Django 2.0.4 on 2019-09-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190904_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='abstract',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
