# Generated by Django 2.0.4 on 2019-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_indicatorvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsector',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
