# Generated by Django 2.0.4 on 2019-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_subsector_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='code',
            new_name='province_code',
        ),
    ]
