# Generated by Django 2.0.4 on 2019-09-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190906_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='code',
            new_name='district_code',
        ),
    ]
