# Generated by Django 2.2.5 on 2019-09-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190906_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsector',
            old_name='data',
            new_name='sub_sector_code',
        ),
    ]
