# Generated by Django 2.2.5 on 2019-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190909_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='sub_sector',
        ),
        migrations.AddField(
            model_name='program',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='SubSector', to='core.SubSector'),
        ),
    ]
