# Generated by Django 2.0.5 on 2019-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190909_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='Psector', to='core.Sector'),
        ),
    ]
