# Generated by Django 2.0.5 on 2019-09-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_program_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='marker_category',
            field=models.ManyToManyField(blank=True, related_name='Pmarkercategory', to='core.MarkerCategory'),
        ),
    ]
