# Generated by Django 2.0.5 on 2019-09-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_program_marker_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('category_population', models.CharField(blank=True, max_length=100, null=True)),
                ('geography', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_value', models.CharField(blank=True, max_length=100, null=True)),
                ('gapanapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TgapaNapa', to='core.GapaNapa')),
            ],
        ),
    ]
