# Generated by Django 2.0.5 on 2019-09-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_traveltime_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanapa',
            name='geography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gapanapa',
            name='population',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
