# Generated by Django 2.0.5 on 2019-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190916_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveltime',
            old_name='category_population',
            new_name='facility_type',
        ),
        migrations.RemoveField(
            model_name='traveltime',
            name='geography',
        ),
        migrations.AddField(
            model_name='traveltime',
            name='tc_pc_pop',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='traveltime',
            name='travel_category_population',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
