# Generated by Django 2.0.5 on 2019-09-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190916_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltime',
            name='population',
        ),
    ]
