# Generated by Django 2.0.5 on 2019-09-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_traveltime_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveltime',
            old_name='travel_value',
            new_name='travel_category',
        ),
    ]
