# Generated by Django 2.0.5 on 2019-09-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190916_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='province_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='province_name',
            new_name='name',
        ),
    ]
