# Generated by Django 2.0.5 on 2019-09-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190925_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='province',
            new_name='province_id',
        ),
    ]
