# Generated by Django 2.0.5 on 2019-09-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190925_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gapanapa',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='gapanapa',
            old_name='province',
            new_name='province_id',
        ),
    ]
