# Generated by Django 2.0.5 on 2019-09-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190925_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markercategory',
            old_name='marker_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='markervalues',
            old_name='marker_category',
            new_name='marker_category_id',
        ),
        migrations.RenameField(
            model_name='markervalues',
            old_name='marker_values',
            new_name='value',
        ),
    ]
