# Generated by Django 2.0.5 on 2019-09-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190926_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_name',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='partner',
            field=models.ManyToManyField(blank=True, related_name='Ppartner', to='core.Partner'),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=50),
        ),
    ]
