# Generated by Django 2.0.5 on 2019-09-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_program_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='budget',
        ),
    ]
