# Generated by Django 2.0.5 on 2019-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190930_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
