# Generated by Django 2.0.5 on 2019-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_program_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_name',
            new_name='contact_person_email',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_person_ph',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/partner/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
