# Generated by Django 2.0.5 on 2019-10-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20191001_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markervalues',
            name='marker_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MarkerCategory', to='core.MarkerCategory'),
        ),
    ]
