# Generated by Django 2.0.5 on 2019-10-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_gislayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gislayer',
            name='type',
            field=models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], default='vector', max_length=50),
        ),
    ]
