# Generated by Django 2.0.5 on 2019-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20191017_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='gislayer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
