# Generated by Django 2.0.5 on 2019-10-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_gislayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gislayer',
            name='geoserver_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
