# Generated by Django 2.0.5 on 2019-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20191018_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='federal_level',
            field=models.CharField(choices=[('palika level', 'Palika Level'), ('district level', 'District Level'), ('province level', 'Province Level')], default='palika level', max_length=50),
        ),
    ]
