# Generated by Django 2.0.5 on 2019-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20191019_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='gislayer',
            name='store_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
