# Generated by Django 2.0.5 on 2019-11-06 05:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanapa',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
