# Generated by Django 2.0.5 on 2019-11-07 07:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_gapanapa_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
