# Generated by Django 2.0.5 on 2019-11-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_district_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_ph', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_person_ph',
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PartnerContact', to='core.Partner'),
        ),
    ]
