# Generated by Django 2.0.5 on 2019-11-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20191111_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnercontact',
            old_name='contact_person_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='partnercontact',
            old_name='contact_person_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='partnercontact',
            old_name='contact_person_ph',
            new_name='phone_number',
        ),
    ]
