# Generated by Django 2.0.5 on 2019-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20191111_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ManyToManyField(blank=True, related_name='ProjectProgram', to='core.Partner'),
        ),
    ]
