# Generated by Django 2.0.5 on 2019-11-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_project_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partner',
        ),
    ]
