# Generated by Django 2.0.5 on 2019-11-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20191113_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivew',
            old_name='implenting_partner_first',
            new_name='implementing_partner_first',
        ),
        migrations.RenameField(
            model_name='fivew',
            old_name='implenting_partner_fourth',
            new_name='implementing_partner_fourth',
        ),
        migrations.RenameField(
            model_name='fivew',
            old_name='implenting_partner_second',
            new_name='implementing_partner_second',
        ),
        migrations.RenameField(
            model_name='fivew',
            old_name='implenting_partner_third',
            new_name='implementing_partner_third',
        ),
        migrations.RenameField(
            model_name='fivew',
            old_name='gapa_napa',
            new_name='municipality',
        ),
    ]
