# Generated by Django 2.0.5 on 2019-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20191113_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=50),
        ),
    ]
