# Generated by Django 2.0.5 on 2019-11-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_fivew_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, max_length=100, null=True)),
                ('male_forecast_2011_2015', models.IntegerField(blank=True, null=True)),
                ('female_forecast_2011_2015', models.IntegerField(blank=True, null=True)),
                ('male_achieved_2011_2015', models.IntegerField(blank=True, null=True)),
                ('female_achieved_2011_2015', models.IntegerField(blank=True, null=True)),
                ('male_forecast_2015_2019', models.IntegerField(blank=True, null=True)),
                ('female_forecast_2015_2019', models.IntegerField(blank=True, null=True)),
                ('male_achieved_2015_2019', models.IntegerField(blank=True, null=True)),
                ('female_achieved_2015_2019', models.IntegerField(blank=True, null=True)),
                ('male_forecast_2011_2019', models.IntegerField(blank=True, null=True)),
                ('female_forecast_2011_2019', models.IntegerField(blank=True, null=True)),
                ('male_achieved_2011_2019', models.IntegerField(blank=True, null=True)),
                ('female_achieved_2011_2019', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
