# Generated by Django 2.0.5 on 2019-11-22 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20191120_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
