# Generated by Django 2.0.5 on 2019-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_province_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='disability_achieved_2011_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='disability_achieved_2011_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='disability_achieved_2015_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='disability_forecast_2011_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='disability_forecast_2011_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='disability_forecast_2015_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
