# Generated by Django 2.0.5 on 2019-11-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20191125_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FProject', to='core.Project'),
        ),
    ]
