# Generated by Django 2.0.5 on 2019-12-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_fivew_representative_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='disability_achieved_2011_2015',
            new_name='disability_achieved_2011',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='disability_achieved_2011_2019',
            new_name='disability_achieved_2012',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='disability_forecast_2011_2019',
            new_name='disability_achieved_2013',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='disability_achieved_2015_2019',
            new_name='disability_achieved_2014',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='disability_forecast_2011_2015',
            new_name='disability_achieved_2015',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='disability_forecast_2015_2019',
            new_name='disability_achieved_2016',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_achieved_2011_2015',
            new_name='disability_achieved_2017',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_achieved_2011_2019',
            new_name='disability_achieved_2018',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_achieved_2015_2019',
            new_name='disability_achieved_2019',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_forecast_2011_2015',
            new_name='disability_forecast_2011',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_forecast_2011_2019',
            new_name='disability_forecast_2012',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='female_forecast_2015_2019',
            new_name='disability_forecast_2013',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_achieved_2011_2015',
            new_name='disability_forecast_2014',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_achieved_2011_2019',
            new_name='disability_forecast_2015',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_achieved_2015_2019',
            new_name='disability_forecast_2016',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_forecast_2011_2015',
            new_name='disability_forecast_2017',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_forecast_2011_2019',
            new_name='disability_forecast_2018',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='male_forecast_2015_2019',
            new_name='disability_forecast_2019',
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_achieved_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='female_forecast_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_achieved_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='male_forecast_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_achieved_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2011',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2012',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2013',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2014',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2015',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2016',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2017',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2018',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total_forecast_2019',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
