# Generated by Django 2.0.5 on 2019-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_notification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivew',
            old_name='budget',
            new_name='approved_budget',
        ),
        migrations.AddField(
            model_name='fivew',
            name='budget_of',
            field=models.CharField(choices=[('national', 'National'), ('province', 'Province'), ('district', 'District'), ('municipality', 'Municipality')], default='national', max_length=100),
        ),
        migrations.AddField(
            model_name='fivew',
            name='spend_budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
