# Generated by Django 2.0.5 on 2019-12-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20191217_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivew',
            old_name='approved_budget',
            new_name='contract_value',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='budget_of',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='spend_budget',
        ),
    ]
