# Generated by Django 2.0.5 on 2020-01-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20191223_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivew',
            name='consortium_partner_first_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='consortium_partner_second_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='consortium_partner_third_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='implementing_partner_first_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='implementing_partner_fourth_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='implementing_partner_second_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='implementing_partner_third_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='local_partner_first_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='local_partner_second_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='local_partner_third_id',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='reporting_ministry_line',
        ),
        migrations.AddField(
            model_name='fivew',
            name='allocated_budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='female_beneficiary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='local_partner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='male_beneficiary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='total_beneficiary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
