# Generated by Django 2.0.5 on 2020-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20200107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='project_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fivew',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=100),
        ),
    ]
