# Generated by Django 2.0.5 on 2020-01-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20200107_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivew',
            old_name='partner_id',
            new_name='supplier_id',
        ),
        migrations.AddField(
            model_name='fivew',
            name='second_tier_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SPartner', to='core.Partner'),
        ),
    ]
