# Generated by Django 2.0.5 on 2020-01-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20200107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetToSecondTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BProject', to='core.Project')),
                ('program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BProgram', to='core.Program')),
                ('second_tier_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BPartner', to='core.Partner')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BsPartner', to='core.Partner')),
            ],
        ),
    ]
