# Generated by Django 2.0.5 on 2020-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_budgettosecondtier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivew',
            name='contract_value',
        ),
        migrations.AddField(
            model_name='budgettosecondtier',
            name='contract_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
