# Generated by Django 2.0.5 on 2020-01-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20200108_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetToFirstTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_budget', models.FloatField(blank=True, default=0, null=True)),
                ('spend_budget', models.FloatField(blank=True, default=0, null=True)),
                ('component_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BFProject', to='core.Project')),
                ('program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BFProgram', to='core.Program')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BFPartner', to='core.Partner')),
            ],
        ),
    ]
