# Generated by Django 2.0.5 on 2020-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_partner_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
