# Generated by Django 2.0.5 on 2020-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_partner_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_code',
            new_name='code',
        ),
    ]
