# Generated by Django 2.0.5 on 2020-02-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20200216_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_project_budget', models.FloatField(blank=True, default=0, null=True)),
                ('percentage_in_country', models.FloatField(blank=True, default=0, null=True)),
                ('budget_country_fy', models.FloatField(blank=True, default=0, null=True)),
                ('sro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('collaborate', 'Collaborate'), ('contribute', 'Contribute'), ('aware', 'Aware')], max_length=50, null=True)),
                ('poc', models.CharField(blank=True, max_length=100, null=True)),
                ('poc_email', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CmDistrict', to='core.District')),
                ('municipality_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CmGapaNapa', to='core.GapaNapa')),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CmProvince', to='core.Province')),
            ],
        ),
    ]
