# Generated by Django 2.0.5 on 2020-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_cmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
