# Generated by Django 2.0.5 on 2020-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20200227_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanapa',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
