# Generated by Django 2.0.5 on 2020-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20200331_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='n_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
