# Generated by Django 2.0.5 on 2020-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_district_n_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapanapa',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
