# Generated by Django 2.0.5 on 2020-04-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_indicator_is_covid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('indicator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FilterIndicator', to='core.Indicator')),
            ],
        ),
    ]
