# Generated by Django 2.0.5 on 2020-04-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='filter_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='filter',
            name='indicator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='core.Indicator'),
        ),
    ]
