# Generated by Django 2.0.5 on 2020-04-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20200415_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('field_color', models.CharField(blank=True, max_length=100, null=True)),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('field_opacity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gislayer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GisStyle', to='core.GisStyle'),
        ),
    ]
