# Generated by Django 2.0.5 on 2020-04-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20200417_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gislayer',
            name='style',
        ),
        migrations.AddField(
            model_name='gisstyle',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GisStyle', to='core.GisLayer'),
        ),
    ]
