# Generated by Django 2.0.5 on 2020-04-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_ttmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttmp',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='municipality_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='supplier_id',
        ),
        migrations.DeleteModel(
            name='Ttmp',
        ),
    ]
