# Generated by Django 2.2.10 on 2020-04-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20200428_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='show_flag',
            field=models.BooleanField(default=False),
        ),
    ]
