# Generated by Django 2.2.10 on 2020-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_indicator_show_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='data_type',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
