# Generated by Django 2.2.10 on 2020-05-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20200501_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Idistrict', to='core.District'),
        ),
    ]
