# Generated by Django 2.2.10 on 2020-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_indicatorvalue_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='federal_level',
            field=models.CharField(choices=[('all', 'All'), ('palika', 'Palika Level'), ('district', 'District Level'), ('province', 'Province Level')], default='palika level', max_length=50),
        ),
    ]
