# Generated by Django 2.2.10 on 2020-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20200527_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='program',
            name='marker_category',
        ),
        migrations.RemoveField(
            model_name='program',
            name='marker_value',
        ),
        migrations.RemoveField(
            model_name='program',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='program',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='program',
            name='sub_sector',
        ),
        migrations.AddField(
            model_name='program',
            name='difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='reported',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='reported_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='total_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='unallocated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='unreported_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='marker_category',
            field=models.ManyToManyField(blank=True, related_name='Pmarkercategory', to='core.MarkerCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='marker_value',
            field=models.ManyToManyField(blank=True, related_name='MarkerValues', to='core.MarkerValues'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='Psector', to='core.Sector'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='SubSector', to='core.SubSector'),
        ),
    ]
