# Generated by Django 2.2.10 on 2020-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20200528_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='total_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
