# Generated by Django 2.2.10 on 2020-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20200528_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='covid_priority_3_12_Months',
            field=models.CharField(blank=True, choices=[('NA - Complete', 'NA - Complete'), ('Yes', 'Yes'), ('Partial High', 'Partial High'), ('Partial Low', 'Partial Low'), ('No', 'No')], default='No', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='covid_recovery_priority',
            field=models.CharField(blank=True, choices=[('NA - Complete', 'NA - Complete'), ('Yes', 'Yes'), ('Partial High', 'Partial High'), ('Partial Low', 'Partial Low'), ('No', 'No')], default='No', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='delivery_in_lockdown',
            field=models.CharField(blank=True, choices=[('NA - Complete', 'NA - Complete'), ('Yes', 'Yes'), ('Partial High', 'Partial High'), ('Partial Low', 'Partial Low'), ('No', 'No')], default='No', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='kathmandu_activity',
            field=models.CharField(blank=True, choices=[('Intervention', 'Intervention'), ('Influence', 'Influence'), ('N/A', 'N/A')], default='N/A', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='providing_ta_to_local_government',
            field=models.CharField(blank=True, choices=[('NA - Complete', 'NA - Complete'), ('Yes', 'Yes'), ('Partial High', 'Partial High'), ('Partial Low', 'Partial Low'), ('No', 'No')], default='No', max_length=500, null=True),
        ),
    ]
