# Generated by Django 2.2.10 on 2020-06-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20200529_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gisstyle',
            old_name='field_color',
            new_name='circle_color',
        ),
        migrations.RenameField(
            model_name='gisstyle',
            old_name='field_opacity',
            new_name='circle_radius',
        ),
        migrations.RenameField(
            model_name='gisstyle',
            old_name='style',
            new_name='fill_color',
        ),
        migrations.RemoveField(
            model_name='gisstyle',
            name='opacity',
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
