# Generated by Django 2.2.10 on 2020-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20200605_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivew',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='female_beneficiary',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='local_partner',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='male_beneficiary',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='total_beneficiary',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='ward',
        ),
        migrations.AddField(
            model_name='fivew',
            name='second_tier_partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
