# Generated by Django 2.2.10 on 2020-06-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20200605_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='marker_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='marker_value',
        ),
        migrations.AddField(
            model_name='program',
            name='marker_category',
            field=models.ManyToManyField(blank=True, related_name='Pmarkercategory', to='core.MarkerCategory'),
        ),
        migrations.AddField(
            model_name='program',
            name='marker_value',
            field=models.ManyToManyField(blank=True, related_name='MarkerValues', to='core.MarkerValues'),
        ),
    ]
