# Generated by Django 2.2.10 on 2020-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20200615_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepalSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
