# Generated by Django 2.2.10 on 2020-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_nepalsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='iati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
