# Generated by Django 2.2.10 on 2020-08-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20200630_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='is_covid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='show_flag',
            field=models.BooleanField(default=True),
        ),
    ]
