# Generated by Django 2.2.10 on 2021-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20200802_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapanapa',
            name='hlcit_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
