# Generated by Django 2.2.10 on 2021-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20210128_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivew',
            name='contact_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='contact_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fivew',
            name='reporting_line_ministry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
