# Generated by Django 2.2.10 on 2021-01-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20210128_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='second_tier_partner_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fivew',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=500),
        ),
    ]
