# Generated by Django 2.2.10 on 2021-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20210128_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='second_tier_partner_name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
