# Generated by Django 2.2.10 on 2021-02-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20210128_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_of_institution',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('International NGO', 'International NGO'), ('National NGO', 'National NGO'), ('Multilateral', 'Multilateral'), ('Private Sector', 'Private Sector'), ('Intergovernmental Organization', 'Intergovernmental Organization'), ('Academic, Training and Research', 'Academic, Training and Research')], max_length=100, null=True),
        ),
    ]
