# Generated by Django 2.2.10 on 2021-02-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20210219_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
    ]
