# Generated by Django 2.2.10 on 2021-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_program_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='Progsector', to='core.Sector'),
        ),
        migrations.AddField(
            model_name='program',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='ProgSubSector', to='core.SubSector'),
        ),
        migrations.RemoveField(
            model_name='program',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='program',
            name='partner_id',
            field=models.ManyToManyField(blank=True, related_name='Progpartner', to='core.Partner'),
        ),
    ]
