# Generated by Django 2.2.10 on 2021-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20210222_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cmp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
