# Generated by Django 2.2.10 on 2021-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20210222_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_acronym',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='component_acronym',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
