# Generated by Django 2.2.10 on 2021-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20210223_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
