# Generated by Django 2.2.10 on 2021-02-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20210225_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Iprovince', to='core.Province'),
        ),
    ]
