# Generated by Django 2.2.10 on 2021-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_indicatorvalue_province_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='budget_spend',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_spend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
