# Generated by Django 2.2.10 on 2021-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20210302_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='status',
            field=models.CharField(blank=True, choices=[('Hold', 'Hold'), ('New', 'New'), ('Old', 'Old')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='budget_spend',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='total_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
