# Generated by Django 2.2.10 on 2021-03-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20210303_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], max_length=500, null=True),
        ),
    ]
