# Generated by Django 2.2.10 on 2021-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20210304_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=500),
        ),
    ]
