# Generated by Django 2.2.10 on 2021-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20210304_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
