# Generated by Django 2.2.10 on 2021-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20210304_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
