# Generated by Django 2.2.10 on 2021-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20210304_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
