# Generated by Django 2.2.10 on 2021-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20210310_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
