# Generated by Django 2.2.10 on 2021-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20210310_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
