# Generated by Django 2.2.10 on 2021-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20210318_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivew',
            name='second_tier_partner_name',
            field=models.CharField(blank=True, max_length=3500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
