# Generated by Django 2.2.10 on 2021-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_auto_20210323_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
