# Generated by Django 2.2.10 on 2021-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20210323_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
