# Generated by Django 2.2.10 on 2021-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_program_sector_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='sector_budget',
            field=models.TextField(blank=True, null=True),
        ),
    ]
