# Generated by Django 2.2.10 on 2021-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20210330_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
