# Generated by Django 2.2.10 on 2021-04-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20210406_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
