# Generated by Django 2.2.10 on 2021-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_nationalstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='district_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='national_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='province_average',
            field=models.FloatField(default=0),
        ),
    ]
