# Generated by Django 2.2.10 on 2021-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20210420_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_regional_profile',
            field=models.BooleanField(default=True),
        ),
    ]
