# Generated by Django 2.2.10 on 2021-04-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_indicator_is_regional_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalstatistic',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
