# Generated by Django 3.2 on 2021-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='your_feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fivew',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='ongoing', max_length=1500),
        ),
    ]
