# Generated by Django 3.2 on 2021-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20210513_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='your_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
