# Generated by Django 3.2 on 2024-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20240319_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='partner_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='Progpartner', to='core.Partner'),
        ),
    ]
