# Generated by Django 2.0.5 on 2020-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttmp',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='ttmp',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='ttmp',
            name='partner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ttmp',
            name='program',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ttmp',
            name='program_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ttmp',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
