# Generated by Django 2.0.5 on 2020-04-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20200420_1531'),
        ('covid', '0002_auto_20200420_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ttmp',
            new_name='CovidFivew',
        ),
    ]
