# Generated by Django 2.0.5 on 2020-04-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200420_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidfivew',
            name='program_code',
        ),
        migrations.RemoveField(
            model_name='covidfivew',
            name='project_code',
        ),
        migrations.AddField(
            model_name='covidfivew',
            name='sector',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
