# Generated by Django 2.0.5 on 2020-04-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20200420_1531'),
        ('covid', '0004_auto_20200420_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_5', models.CharField(blank=True, max_length=20, null=True)),
                ('f_10', models.CharField(blank=True, max_length=20, null=True)),
                ('f_15', models.CharField(blank=True, max_length=20, null=True)),
                ('f_20', models.CharField(blank=True, max_length=20, null=True)),
                ('f_25', models.CharField(blank=True, max_length=20, null=True)),
                ('f_30', models.CharField(blank=True, max_length=20, null=True)),
                ('f_35', models.CharField(blank=True, max_length=20, null=True)),
                ('f_40', models.CharField(blank=True, max_length=20, null=True)),
                ('f_45', models.CharField(blank=True, max_length=20, null=True)),
                ('f_50', models.CharField(blank=True, max_length=20, null=True)),
                ('f_55', models.CharField(blank=True, max_length=20, null=True)),
                ('f_60', models.CharField(blank=True, max_length=20, null=True)),
                ('f_65', models.CharField(blank=True, max_length=20, null=True)),
                ('f_70', models.CharField(blank=True, max_length=20, null=True)),
                ('f_75', models.CharField(blank=True, max_length=20, null=True)),
                ('f_80', models.CharField(blank=True, max_length=20, null=True)),
                ('m_5', models.CharField(blank=True, max_length=20, null=True)),
                ('m_10', models.CharField(blank=True, max_length=20, null=True)),
                ('m_15', models.CharField(blank=True, max_length=20, null=True)),
                ('m_20', models.CharField(blank=True, max_length=20, null=True)),
                ('m_25', models.CharField(blank=True, max_length=20, null=True)),
                ('m_30', models.CharField(blank=True, max_length=20, null=True)),
                ('m_35', models.CharField(blank=True, max_length=20, null=True)),
                ('m_40', models.CharField(blank=True, max_length=20, null=True)),
                ('m_45', models.CharField(blank=True, max_length=20, null=True)),
                ('m_50', models.CharField(blank=True, max_length=20, null=True)),
                ('m_55', models.CharField(blank=True, max_length=20, null=True)),
                ('m_60', models.CharField(blank=True, max_length=20, null=True)),
                ('m_65', models.CharField(blank=True, max_length=20, null=True)),
                ('m_70', models.CharField(blank=True, max_length=20, null=True)),
                ('m_75', models.CharField(blank=True, max_length=20, null=True)),
                ('m_80', models.CharField(blank=True, max_length=20, null=True)),
                ('male_total', models.CharField(blank=True, max_length=20, null=True)),
                ('female_total', models.CharField(blank=True, max_length=20, null=True)),
                ('male_high_risk', models.CharField(blank=True, max_length=20, null=True)),
                ('female_high_risk', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('all_high_risk', models.CharField(blank=True, max_length=20, null=True)),
                ('all_risk_pct', models.CharField(blank=True, max_length=20, null=True)),
                ('male_high_pct', models.CharField(blank=True, max_length=20, null=True)),
                ('female_high_pct', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DryDeshospSum',
            fields=[
                ('commonfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.CommonField')),
                ('grid_code', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=500, null=True)),
                ('category_code', models.CharField(blank=True, max_length=10, null=True)),
                ('category_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('type_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ownership_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_num', models.CharField(blank=True, max_length=100, null=True)),
                ('used_for_corona_response', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_bed', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_icu_bed', models.CharField(blank=True, max_length=10, null=True)),
                ('occupied_icu_bed', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_ventilators', models.CharField(blank=True, max_length=10, null=True)),
                ('occupied_ventilators', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_isolation_bed', models.CharField(blank=True, max_length=10, null=True)),
                ('occupied_isolation_bed', models.CharField(blank=True, max_length=10, null=True)),
                ('total_tested', models.CharField(blank=True, max_length=10, null=True)),
                ('total_positive', models.CharField(blank=True, max_length=10, null=True)),
                ('total_death', models.CharField(blank=True, max_length=10, null=True)),
                ('total_in_isolation', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('covid.commonfield',),
        ),
        migrations.CreateModel(
            name='DryDeshospUncoveredAdm1Sums',
            fields=[
                ('commonfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.CommonField')),
                ('object_code', models.CharField(blank=True, max_length=20, null=True)),
                ('fid_adm1', models.CharField(blank=True, max_length=20, null=True)),
                ('sum_11', models.CharField(blank=True, max_length=20, null=True)),
                ('wp_sum', models.CharField(blank=True, max_length=20, null=True)),
                ('hrsl_sum', models.CharField(blank=True, max_length=20, null=True)),
                ('fid_dry_de', models.CharField(blank=True, max_length=20, null=True)),
                ('object_id_1', models.CharField(blank=True, max_length=20, null=True)),
                ('palika_1', models.CharField(blank=True, max_length=500, null=True)),
                ('district_1', models.CharField(blank=True, max_length=500, null=True)),
                ('gapa_napa_1', models.CharField(blank=True, max_length=500, null=True)),
                ('province_1', models.CharField(blank=True, max_length=500, null=True)),
                ('shape_length', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_area', models.CharField(blank=True, max_length=50, null=True)),
                ('uncov_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('covid.commonfield',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs12hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs12hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs4hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs4hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs8hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryAllCovidsDhfs8hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.CreateModel(
            name='DryDshosp12hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryDshosp12hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.CreateModel(
            name='DryDshosp4hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryDshosp4hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.CreateModel(
            name='DryDshosp8hrSums',
            fields=[
                ('drydeshospsum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospSum')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospsum',),
        ),
        migrations.CreateModel(
            name='DryDshosp8hrUncoveredAdm1Sums',
            fields=[
                ('drydeshospuncoveredadm1sums_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.DryDeshospUncoveredAdm1Sums')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('covid.drydeshospuncoveredadm1sums',),
        ),
        migrations.AddField(
            model_name='drydeshospuncoveredadm1sums',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrUncoveredAdm1Sums', to='core.District'),
        ),
        migrations.AddField(
            model_name='drydeshospuncoveredadm1sums',
            name='municipality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrUncoveredAdm1Sums', to='core.GapaNapa'),
        ),
        migrations.AddField(
            model_name='drydeshospuncoveredadm1sums',
            name='province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrUncoveredAdm1Sums', to='core.Province'),
        ),
        migrations.AddField(
            model_name='drydeshospsum',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrSum', to='core.District'),
        ),
        migrations.AddField(
            model_name='drydeshospsum',
            name='municipality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrSum', to='core.GapaNapa'),
        ),
        migrations.AddField(
            model_name='drydeshospsum',
            name='province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DryDeshosp4hrSum', to='core.Province'),
        ),
    ]
