# Generated by Django 2.2.10 on 2020-04-30 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_indicator_show_flag'),
        ('covid', '0006_auto_20200421_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidSpecificProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CvsDistrict', to='core.District')),
                ('municipality_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CvsGapaNapa', to='core.GapaNapa')),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CvsProvince', to='core.Province')),
            ],
        ),
    ]
