# Generated by Django 2.0.4 on 2019-08-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190813_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization', to='core.Organization')),
                ('program_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Program', to='core.Program')),
            ],
        ),
    ]
