# Generated by Django 2.0.4 on 2019-08-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190819_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivew',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='fivew',
            name='program_name',
        ),
        migrations.DeleteModel(
            name='FiveW',
        ),
    ]
