# Generated by Django 2.0.5 on 2019-11-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_project'),
        ('dashboard', '0007_auto_20191105_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePartner', to='core.Partner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProgram', to='core.Program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProject', to='core.Project'),
        ),
    ]
