# Generated by Django 2.0.5 on 2020-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191129_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='upload/profile/'),
        ),
    ]
