# Generated by Django 2.2.10 on 2021-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userprofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='upload/profile/'),
        ),
    ]
