# Generated by Django 2.2.10 on 2020-04-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='districtboundary',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gapanapaboundary',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='provinceboundary',
            managers=[
            ],
        ),
    ]
