# Generated by Django 2.2.10 on 2020-04-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_auto_20200428_1327'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='provinceboundary',
            managers=[
            ],
        ),
    ]
