# Generated by Django 4.1 on 2024-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("federal", "0004_auto_20200428_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gapanapaboundary",
            name="district_id",
        ),
        migrations.RemoveField(
            model_name="gapanapaboundary",
            name="province_id",
        ),
        migrations.DeleteModel(
            name="DistrictBoundary",
        ),
        migrations.DeleteModel(
            name="GapaNapaBoundary",
        ),
        migrations.DeleteModel(
            name="ProvinceBoundary",
        ),
    ]
