name: Deploy Backend of dvsphase2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_backend:
    name: Deploy Backend on AWS
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance and deploy backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-13-201-60-41.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get into Backend Directory
        run: |
          cd /home/ubuntu/Projects/dvsphase2

      - name: Pull code form GitHub
        run: |
          git pull origin develop

      - name: Build and turn Docker Compose Up
        run:
          docker-compose up -d --build